{{- if .Values.sdsReplicatedVolume.newControlPlane }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "agent")) | nindent 2 }}
data:
  slogh.cfg: |
    # those are all keys with default values:

    # any slog level, or just a number
    level=INFO

    # also supported: "text"
    format=json

    # for each log print "source" property with information about callsite
    callsite=false

    render=true
    stringValues=true
{{- end }}
