{{- define "sds_drbd_controller_resources" }}
cpu: 10m
memory: 25Mi
{{- end }}

{{- if (.Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: controller
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "controller")) | nindent 2 }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: controller
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: "controller"
      minAllowed:
        {{- include "sds_drbd_controller_resources" . | nindent 8 }}
      maxAllowed:
        cpu: 200m
        memory: 100Mi
{{- end }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: controller
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "controller" )) | nindent 2 }}
spec:
  minAvailable: {{ include "helm_lib_is_ha_to_value" (list . 1 0) }}
  selector:
    matchLabels:
      app: controller
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "controller")) | nindent 2 }}
spec:
  revisionHistoryLimit: 2
  {{- include "helm_lib_deployment_strategy_and_replicas_for_ha" . | nindent 2 }}
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      {{- include "helm_lib_priority_class" (tuple . "cluster-medium") | nindent 6 }}
      {{- include "helm_lib_node_selector" (tuple . "system") | nindent 6 }}
      {{- include "helm_lib_tolerations" (tuple . "system") | nindent 6 }}
      {{- include "helm_lib_module_pod_security_context_run_as_user_nobody" . | nindent 6 }}
      {{- include "helm_lib_pod_anti_affinity_for_ha" (list . (dict "app" "controller")) | nindent 6 }}
      imagePullSecrets:
        - name: {{ .Chart.Name }}-module-registry
      serviceAccountName: controller
      containers:
        - name: controller
          image: {{ include "helm_lib_module_image" (list . "controller") }}
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /readyz
              port: 4271
              scheme: HTTP
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4271
              scheme: HTTP
            periodSeconds: 1
            failureThreshold: 3
          resources:
            requests:
              {{- include "helm_lib_module_ephemeral_storage_only_logs" . | nindent 14 }}
{{- if not ( .Values.global.enabledModules | has "vertical-pod-autoscaler-crd") }}
              {{- include "sds_drbd_controller_resources" . | nindent 14 }}
{{- end }}
          # TODO: disable seccomp-profile check - seccompProfile not specified
          # TODO: disable no-new-privileges check - AllowPrivilegeEscalation not specified
          securityContext:
            privileged: true
            readOnlyRootFilesystem: true
            seLinuxOptions:
              level: s0
              type: spc_t
          env:
            - name: SLOGH_CONFIG_PATH
              value: "/etc/config/slogh.cfg"
          volumeMounts:
            - name: host-device-dir
              mountPath: /dev/
            - name: host-sys-dir
              mountPath: /sys/
            - name: host-root
              mountPath: /host-root/
              mountPropagation: HostToContainer
            - mountPath: /etc/config/
              name: config
      volumes:
        - name: host-device-dir
          hostPath:
            path: /dev
            type: ""
        - name: host-sys-dir
          hostPath:
            path: /sys/
            type: Directory
        - name: host-root
          hostPath:
            path: /
        - name: config
          configMap:
            name: controller-config
            items:
              - key: slogh.cfg
                path: slogh.cfg
