---
apiVersion: v1
kind: ConfigMap
metadata:
  name: d8-{{ .Chart.Name }}-drbd-versions
  namespace: d8-{{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list .) | nindent 2 }}
data:
  allowedDrbdVersions: |
    9.2.13
    9.2.16
